### ISSUE TITLE
Package versions?

### ISSUE THREAD

**Issue by nfitch3** [dvgodoy/deepreplay#23]
Can you tell me what package versions of tensorflow and keras I should be using in order to run this code? Specifically, the example I've been trying to recreate is from your post [here](https://towardsdatascience.com/hyper-parameters-in-action-part-ii-weight-initializers-35aee1a28404).

I see the requirements.txt says tensorflow==1.5.0 but that doesn't appear to be a distribution available through pip.

**Comment by dvgodoy** [comment]
Hi,
I've developed this 2 years ago, it was supposed to work with TF 1.X and Keras 2.2.0.
It surely DOES NOT work with TF 2.X and Keras versions compatible with it, because it was radically changed.
You could try with TF 1.15 (but I can't guarantee it will work, I haven't tried using that version).
Hope it helps.

**Comment by nfitch3** [comment]
@dvgodoy thanks for your reply and the deepreplay package! I will try your suggestion but I believe I may have tried TF 1.15 already, but will double check it. Do you happen to remember what versions of keras/tensorflow that you used specifically in some of your examples?

Also, are you continuing development for this package or have you found better alternatives since developing it? Thanks again for your code!

**Comment by dvgodoy** [comment]
Hi,
I believe it as TF 1.8 and Keras 2.2.3.
Unfortunately, I am likely not continuing development... TF 2 broke most of my code, it would require a lot time and effort to rewrite it.
